package me.bartoszrobakowski.unquote;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Questions {
    public static final List<Question> QUESTIONS = new ArrayList<>(
            Arrays.asList(
                    new Question(R.drawable.img_quote_0,
                            "Pretty good advice and perhaps a scientist did say it… Who actually did??",
                            "Albert Einstein",
                            "Isaac Newton",
                            "Rita Mae Brown",
                            "Rosalind Franklin",
                            2),
                    new Question(R.drawable.img_quote_1,
                            "Was honest Abe honestly quoted? Who authored this pithy bit of wisdom?",
                            "Edward Stieglitz",
                            "Maya Angelou",
                            "Abraham Lincoln",
                            "Ralph Waldo Emerson",
                            0),
                    new Question(R.drawable.img_quote_2,
                            "Easy advice to read difficult advice to follow — who actually said it?",
                            "Martin Luther King Jr.",
                            "Mother Teresa",
                            "Fred Rogers",
                            "Oprah Winfrey",
                            1),
                    new Question(R.drawable.img_quote_3,
                            "Insanely inspiring insanely incorrect (maybe). Who is the true source of this inspiration?",
                            "Nelson Mandela",
                            "Harriet Tubman",
                            "Mahatma Gandhi",
                            "Nicholas Klein",
                            3),
                    new Question(R.drawable.img_quote_4,
                            "A peace worth striving for — who actually reminded us of this?",
                            "Malala Yousafzai",
                            "Martin Luther King Jr.",
                            "Liu Xiaobo",
                            "Dalai Lama",
                            1),
                    new Question(R.drawable.img_quote_5,
                            "Unfortunately, true — but did Marilyn Monroe convey it or did someone else?",
                            "Laurel Thatcher Ulrich",
                            "Eleanor Roosevelt",
                            "Marilyn Monroe",
                            "Queen Victoria",
                            0),
                    new Question(R.drawable.img_quote_6,
                            "Here’s the truth, Will Smith did say this, but in which movie?",
                            "\"Independence Day\"",
                            "\"Bad Boys\"",
                            "\"Men In Black\"",
                            "\"The Pursuit of Happyness\"",
                            2),
                    new Question(R.drawable.img_quote_7,
                            "Which TV funny gal actually quipped this 1-liner?",
                            "Ellen Degeneres",
                            "Amy Poehler",
                            "Betty White",
                            "Tina Fay",
                            3),
                    new Question(R.drawable.img_quote_8,
                            "This mayor won’t get my vote — but did he actually give this piece of advice? And if not, who did?",
                            "Forrest Gump\n\"Forrest Gump\"",
                            "Dorry\n\"Finding Nemo\"",
                            "Esther Williams",
                            "The Mayor\n\"Jaws\"",
                            1),
                    new Question(R.drawable.img_quote_9,
                            "Her heart will go on, but whose heart is it?",
                            "Whitney Houston",
                            "Diana Ross",
                            "Celine Dion",
                            "Mariah Carey",
                            0),
                    new Question(R.drawable.img_quote_10,
                            "He’s the king of something alright — to whom does this self-titling line belong to?",
                            "Tony Montana\n\"Scarface\"",
                            "Joker\n\"The Dark Knight\"",
                            "Lex Luthor\n\"Batman v Superman\"",
                            "Jack\n\"Titanic\"",
                            3),
                    new Question(R.drawable.img_quote_11,
                            "Is “Grey” synonymous for “wise”? If so, maybe Gandalf did preach this advice. If not, who did?",
                            "Yoda\n\"Star Wars\"",
                            "Gandalf The Grey\n\"Lord of the Rings\"",
                            "Dumbledore\n\"Harry Potter\"",
                            "Uncle Ben\n\"Spider-Man\"",
                            0),
                    new Question(R.drawable.img_quote_12,
                            "Houston, we have a problem with this quote — which space-traveler does this catch-phrase actually belong to?",
                            "Han Solo\n\"Star Wars\"",
                            "Captain Kirk\n\"Star Trek\"",
                            "Buzz Lightyear\n\"Toy Story\"",
                            "Jim Lovell\n\"Apollo 13\"",
                            2)
            )
    );
}
